server:
  port: 8050
spring:
  application:
    name: turbine
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
    - name:defaultZone
      value:http://localhost:8761/eureka/
  instance:
    ip-address: true