server:
  port: 8040
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      - name:defaultZone
        value:http://localhost:8761/eureka
zuul:
  routes:
    - name:
      value:http://localhost:8761/eureka
